"""Add user_wallet_address and privy_wallet_address fields

Revision ID: 9f77a78fe015
Revises: e4e5c12e1e55
Create Date: 2025-12-29 16:45:53.843700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f77a78fe015'
down_revision: Union[str, Sequence[str], None] = 'e4e5c12e1e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('user_wallet_address', sa.String(length=42), nullable=True))
    op.add_column('robots', sa.Column('privy_wallet_address', sa.String(length=42), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robots', 'privy_wallet_address')
    op.drop_column('robots', 'user_wallet_address')
    # ### end Alembic commands ###
