"""Add deleted_at for soft delete

Revision ID: e4e5c12e1e55
Revises: f54f7ea93b39
Create Date: 2025-12-29 15:24:15.726472

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e4e5c12e1e55'
down_revision: str | Sequence[str] | None = 'f54f7ea93b39'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robots', 'deleted_at')
    # ### end Alembic commands ###
