"""Create robots table

Revision ID: f54f7ea93b39
Revises:
Create Date: 2025-12-29 15:01:39.801035

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f54f7ea93b39'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('motor_ip', sa.String(length=45), nullable=False),
    sa.Column('camera_ip', sa.String(length=45), nullable=False),
    sa.Column('motor_mdns', sa.String(length=253), nullable=True),
    sa.Column('camera_mdns', sa.String(length=253), nullable=True),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('wallet_source', sa.Enum('USER_PROVIDED', 'PRIVY_CREATED', name='walletsource'), nullable=False),
    sa.Column('privy_wallet_id', sa.String(length=100), nullable=True),
    sa.Column('owner_wallet', sa.String(length=253), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('motor_mdns')
    )
    op.create_index(op.f('ix_robots_name'), 'robots', ['name'], unique=True)
    op.create_index(op.f('ix_robots_wallet_address'), 'robots', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_robots_wallet_address'), table_name='robots')
    op.drop_index(op.f('ix_robots_name'), table_name='robots')
    op.drop_table('robots')
    # ### end Alembic commands ###
